### ISSUE TITLE
What does tsconfig.json do in this sample?

### ISSUE THREAD

**Issue by dfenerski** [ui5-community/ui5-ts-shim-showcase#1]
Let me first say a big thank you for the demo. This is something I was looking for.

After playing around with the sample I found something that bugs me. What does the `compilerOptions/paths` property in the sample do, because when I deleted it, nothing changed. Furthermore, I could not get my OSS definitions to work unless I added them **there** explicitly: `"paths": { "currency.js": ["./node_modules/currency.js/dist/currency.d.ts"] }`. 

The pre-configured `typeRoots` seem to work only for definetly typed packages and the ui5 modules ofc, or?

What does the initial value of `compilerOptions/paths` do?
Is it correct to manually add paths to `compilerOptions/paths`?

Thanks in advance

Dimitar

**Comment by wridgeu** [comment]
Hey there,

I might be able to answer at least a few questions. Not all of them sadly, as I'd have to take a closer look into the repository first and my current Notebook isn't fully set up. 

> The pre-configured `typeRoots` seem to work only for definetly typed packages and the ui5 modules ofc, or?

Yep! You can of course adjust the typeRoots to your needs.

> What does the initial value of `compilerOptions/paths` do? 

I'd guess it has to do with running the application during development (as it includes the project path itself with a - at development time non-existant folder `shim`. I'm not a 100% sure why they are included as of now. I think @petermuessig can give a better explanation 😄

> Is it correct to manually add paths to `compilerOptions/paths`?

So far, with what I have done in typescript, I'd say yes. You can of course find more detailed explanations regarding everything in the `tsconfig` file in the official documentation.

- https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
- or more specifc, here: https://www.typescriptlang.org/tsconfig#paths

**Comment by petermuessig** [comment]
I don't know if this question here is still relevant - but some small comments from my side:

- the `tsconfig.json` is mainly relevant for the IDE to provide a proper code completion support and for the `tslint` - for the pure build it is not taken into consideration
- dependencies should nowadays be added into the `types` section and listed individually => this avoids and relative path in your `tsconfig.json` which may break (e.g. in mono repo using different npm package managers)
- the `compilerOptions/paths` is relevant for the mapping of the source files into the UI5 namespaces - which indicates that everything in the src folder is mapped to the namespace `ui5-ts-shim-showcase/shim`
- it works for your OSS library because you point to the concrete `d.ts` file and establish the mapping - but this may also work automatically when adding the `currency.js` to the `types` section (if the OSS library has properly configured his types information)
